[package]
name = "SLICK"
version = "0.2.1"
authors = ["Michael Bednarek <mbednarek360@protonmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen="*"
gloo="*"
rand = "*"
time = "*"
rustc-serialize = "*"

[dependencies.web-sys]
version = "*"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window'
]

[[bin]]
name = "SLICK"
path = "web/main.rs"
