[package]
name = "SLICK"
version = "0.2.1"
authors = ["Michael Bednarek <mbednarek360@protonmail.com>"]
edition = "2018"
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]
path = "web/main.rs"

[dependencies]
wasm-bindgen = "*"
gloo = "*"
rand = "*"
time = "*"
hex = "*"
base64 = "*"

[dependencies.web-sys]
version = "*"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window'
]

[[bin]]
name = "SLICK"
path = "web/main.rs"
