[package]
name = "SLICK"
version = "0.2.1"
authors = ["Michael Bednarek <mbednarek360@protonmail.com>"]
edition = "2018"

[dependencies]
rand = "*"
time = "*"
rustc-serialize = "*"

[[bin]]
name = "SLICK"
path = "cli/main.rs"