name: Package

on:
    workflow_run:
        workflows: ['Build']
        branches: [ master ]
        types:
            - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to Crates.io
      run: cargo publish --token ${{secrets.CRATES_API_KEY}}
